#!/bin/sh

gcc main.o -o game run.o select.o spaceship.o start.o algif.o bitmap.o blast.o boss.o collision.o enemy.o gif.o introduce.o lzw.o restart.o unionship.o weapen.o -L./allegro -lallegro -lallegro_primitives -lallegro_image -lallegro_font -lallegro_ttf -lpthread -lallegro_audio -lallegro_acodec -lm

#！/bin/bash
./game

echo "输入 ./game 开始游戏"
